terraform-2
Otus-DevOps-2022-05/g-turkin_infra pull request #6
Opened 2022-07-13 12:37 UTC by g-turkin

# Выполнено ДЗ № 7 Создание Terraform модулей для управления компонентами инфраструктуры.

2022-07-13 12:42 UTC, g-turkin commented
Добрый день.
Скрипт проверки ругается на след. команды:
Command: `cd packer && packer validate -var-file=variables.json.example ubuntu16.json` stdout should eq "Template validated successfully.\n"
Command: `cd terraform && terraform init -backend=false && terraform validate -var-file=terraform.tfvars.example` exit_status should eq 0

Как и предыдущем ДЗ, на локальной машине все работает.
Просьба принять ДЗ

2022-07-13 14:26 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Не хватает некоторого количества файлов
Нужно их добавить =)

2022-07-13 17:26 UTC, g-turkin commented
Добрый вечер.
Добавил файл terraform.tfvars.example
Просьба проверить.

2022-07-14 12:31 UTC, mrgreyves approved these changes
Здравствуйте!)
Проверил ваше дз
Оставил комментарий к файлу
Кажется что versions.tf лишний, его можно удалить

2022-07-14 12:31 UTC, mrgreyves commented on terraform/modules/db/versions.tf
> +terraform {
Эммм, для чего вы добавили эти файлы?

2022-07-14 16:48 UTC, g-turkin commented on terraform/modules/db/versions.tf
> +terraform {
Их terraform добавил когда добавлял модули app,db,vpc

2022-07-14 16:48 UTC, merged