ansible-1
Otus-DevOps-2022-05/g-turkin_infra pull request #7
Opened 2022-07-18 17:19 UTC by g-turkin

# Выполнено ДЗ № 8 Написание Ansible плейбуков на основе имеющихся bash скриптов

2022-07-18 19:27 UTC, g-turkin commented
Добрый вечер.
Просьба принять ДЗ

2022-07-19 06:41 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Кажется у вас достаточно большое количество проблем с манифестами терраформа из предыдущего дз
Рекомендую свериться с результатами тестов
Если возникнут дополнительные вопросы, оформляйте пр еще раз что бы я смог более предметно вам помочь =)

2022-07-19 07:59 UTC, g-turkin commented
Добрый день.
На локальной машине выполняется и работает без ошибок.
Файлы versions.tf создаются после команды terraform init 

Просьба подсказать в чем может быть причина.

terraform init -backend=false && terraform validate -var-file=terraform.tfvars.example
![image](https://user-images.githubusercontent.com/105578217/179698146-b9515f73-39f9-4f82-b65c-114f9283b19c.png)

2022-07-19 10:51 UTC, g-turkin commented
Тест стал проходить после добавления файлов terraform.tfvars.example  variables.tf в папку terraform, хотя в предыдущем задании была задача их удалить из этой папки
![image](https://user-images.githubusercontent.com/105578217/179733445-43e654d6-1c8c-44d2-98fd-4adb96bdb475.png)

2022-07-19 13:59 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь точно апрув ^_^

2022-07-19 16:43 UTC, merged